import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import dynamic from 'next/dynamic'

const Map = dynamic(
    () => import('../components/Map'), // replace '@components/map' with your component's location
    {
        loading: () => <p>A map is loading</p>,
        ssr: false, // This line is important. It's what prevents server-side render
    }
)

export default function Home() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Next Leaflet</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="stylesheet"
                        href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
                        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
                        crossOrigin=""
                    />
                </Head>
                <Script
                    src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
                    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
                    crossorigin=""
                ></Script>

                <main className={styles.main}>
                    <Map />
                </main>
            </div>
        </>
    )
}
